name: Unit tests
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go test
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: "1.21.3"
      - name: Unit tests
        run: go test -v ./... -timeout 10m
